using System.Diagnostics;

const string PathToVocabularies = "./Source";
var words = new List<string>(2_000_000);
foreach (var file in Directory.EnumerateFiles(PathToVocabularies))
{
    var lines = await File.ReadAllLinesAsync(file);
    words.AddRange(lines);
}

const string OutputFileName = "words.txt";
const long FileCapacityInBytes = 1L * 1024 * 1024 * 1024;
const long WordCount = 60_000_000;

var startTime = Stopwatch.GetTimestamp();
await using var fileStream = File.OpenWrite(OutputFileName);
await using var writer = new StreamWriter(fileStream);
var generator = new Random(1883);
var counter = 0;
while (fileStream.Position < FileCapacityInBytes && counter < WordCount) 
{
    var index = generator.Next(0, words.Count);
    writer.Write(++counter);
    writer.Write('.');
    writer.WriteLine(words[index]);
}
var elapsed = Stopwatch.GetElapsedTime(startTime);
Console.WriteLine($"Words count = {counter}, File size = {fileStream.Position}, Generated by {elapsed.Milliseconds}ms");